# Generated by Django 5.2 on 2025-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issued_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='received_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
