# Generated by Django 5.2 on 2025-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_stock_issued_quantity_stock_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
