# Generated by Django 5.2 on 2025-04-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0003_sales_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_stock',
        ),
    ]
