# Generated by Django 5.2 on 2025-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0004_remove_stock_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='contact',
            field=models.IntegerField(default=20),
        ),
    ]
