# Generated by Django 5.2 on 2025-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0005_alter_credit_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='NIN',
            field=models.CharField(unique=True),
        ),
    ]
