# Generated by Django 5.2 on 2025-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0006_alter_credit_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='location',
            field=models.CharField(default=35, max_length=25),
        ),
    ]
